### PR TITLE
feat: Add affinity value to deployment

### PR DESCRIPTION
**Pull request by casserlyprogramming**
Adds the affinity value so we can assign pods with more options

### CODE REVIEW

**Review by juanpicado — APPROVED** [review]
LGTM, waiting for @verdaccio/kubernetes

**Comment by pshanoop** [comment]
LGTM, @juanpicado   I don't know the process of merging a PR. Should I merge or someone else  ?

**Comment by juanpicado** [comment]
Go ahead @pshanoop !. The @verdaccio/kubernetes group has permissions to merge if is green and at least 2 approvals should be good , so feel free merge 👍🏼

**Comment by juanpicado** [comment]
@pshanoop you would need to approve.

**Review by marekaf — APPROVED** [review]
lgtm

**Comment by Rkallenkoot** [comment]
Literally just looking for this, thanks folks!

**Pull request merged**
