### PR TITLE
add priorityClassName support

### PR DESCRIPTION
**Pull request by marekaf**

### CODE REVIEW

**Comment by juanpicado** [comment]
hi @marekaf thanks for this, please describe detailed your addition.

**Comment by marekaf** [comment]
> hi @marekaf thanks for this, please describe detailed your addition.
Hi @juanpicado,
I added support for priorityClassName in pod spec as this wasn't supported so far.

More info about priority classes:
Pods can have priority. Priority indicates the importance of a Pod relative to other Pods. If a Pod cannot be scheduled, the scheduler tries to preempt (evict) lower priority Pods to make scheduling of the pending Pod possible.

https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

I simply added it to deployment template, default values.yaml and README.

**Comment by juanpicado** [comment]
Thanks @marekaf , I'm not DevOps so any additional info is helpful.

**Comment by marekaf** [comment]
> Thanks @marekaf , I'm not DevOps so any additional info is helpful.

I'm not DevOps either. What else needs to be clarified?

**Comment by juanpicado** [comment]
You need bump up

**Comment by kav** [comment]
Ah yes

**Pull request merged**
