### PR TITLE
feat!: chart as apiVersion 2

### PR DESCRIPTION
**Pull request by juanpicado**
This chart should be based on Helm v3 thus the apiVersion should be `v2`

https://helm.sh/docs/topics/v2_v3_migration/

### CODE REVIEW

**Review by jfrancisco0 — COMMENTED** [review]
You may want to add some upgrade notes (in the README?) to explain the impact of the upgrade, and maybe delete the Helm 2 command examples from there, since they're no longer valid.

**Comment by juanpicado** [comment]
> You may want to add some upgrade notes (in the README?) to explain the impact of the upgrade, and maybe delete the Helm 2 command examples from there, since they're no longer valid.

Fully agree :+1:

**Review by jfrancisco0 — APPROVED** [review]
I think it's fairly clear already, but I'll leave the example from [external-dns](https://github.com/bitnami/charts/tree/master/bitnami/external-dns#to-400), since they have an `Upgrading` section in their README, which I think is pretty neat.

LGTM 👍

**Comment by juanpicado** [comment]
> I think it's fairly clear already, but I'll leave the example from [external-dns](https://github.com/bitnami/charts/tree/master/bitnami/external-dns#to-400), since they have an `Upgrading` section in their README, which I think is pretty neat.
> 
> LGTM

Good references, actually we need that + proper changelog, currently is not pretty clear what have changed. I'll do it in a follow up PR.

**Pull request merged**
