### PR TITLE
remove(deployment): the 'replicas' field from the helm template if not used by user

### PR DESCRIPTION
**Pull request by alexis974**
## What does this MR do?

Remove the 'replicas' field from the helm template if set to null by user.

## Why was this MR needed?

If you are using Keda to auto-scale your runner, it will modify the 'spec.replicas' of the deployment. That will cause a drift from the manifest known to ArgoCD. Therefore ArgoCD resync the resource. But then Keda retry to update it, and so on.....

By modifing the deployment template, we ensure that the replicas field is not present in the helm template if set to null by the user, and therefore not watch by ArgoCD. Note that by default, Kubernetes will set de 'spec.replicas' field to 1 if not present.

## What's the best way to test this MR?

Do three helm template:
  - One with replicaCount to 1
  - One with replicaCount to 0
  - One with replicaCount to null

### CODE REVIEW

**Comment by alexis974** [comment]
Could you take a look @juanpicado ?

**Comment by alexis974** [comment]
Hi @juanpicado, sorry for the long delay.
Could you trigger the workflow again ?

**Comment by alexis974** [comment]
I updated the documentation

**Comment by alexis974** [comment]
I updated the documentation. I seems that you need to re-trigger the workflow @juanpicado . Sorry for that :/

**Review by juanpicado — APPROVED** [review]

**Comment by juanpicado** [comment]
Thanks :)

**Pull request merged**
