### PR TITLE
feature: add caching nginx

### PR DESCRIPTION
**Pull request by shcherbak**
replacement for https://github.com/verdaccio/charts/pull/149

### CODE REVIEW

**Comment by shcherbak** [comment]
@juanpicado  this is update , that Yuo requested https://github.com/verdaccio/charts/pull/149

**Comment by juanpicado** [comment]
> @juanpicado  this is update , that Yuo requested https://github.com/verdaccio/charts/pull/149

You still have some lint issues to check probably bump up 🆙 the chart

**Review by juanpicado — APPROVED** [review]

**Comment by juanpicado** [comment]
Thanks 🙏

**Comment by juanpicado** [comment]
Thanks 🙏

**Pull request merged**
