### PR TITLE
Chore: Verdaccio `5.15.3`

### PR DESCRIPTION
**Pull request by rblaine95**
Update Verdaccio from `5.5.0` to `5.15.3`

I believe this solves #102

### CODE REVIEW

**Comment by juanpicado** [comment]
thanks @rblaine95 let's wait 5.2.13 today will be released, there will be a big booster https://github.com/verdaccio/verdaccio/pull/3364 ref https://github.com/verdaccio/verdaccio/issues/3357#issuecomment-1238970082

**Comment by rblaine95** [comment]
Great, I'll update this PR once `5.2.13` is released 😊

**Comment by juanpicado** [comment]
Now is ready, free free to updated 🙃

**Review by juanpicado — APPROVED** [review]

**Comment by juanpicado** [comment]
Thanks @rblaine95 for taking care 💯

**Pull request merged**
